version: '3.1'

x-logging: &logging
  logging:
    driver: 'json-file'
    options:
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  mysql:
    <<: *logging
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  phpmyadmin:
    <<: *logging
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - UPLOAD_LIMIT=200M
      - PMA_HOST=mysql
    depends_on:
      - mysql

  proxy:
    <<: *logging
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager:latest
    restart: always
    ports:
      - ${PROXY_PORT}:80
      - ${PROXY_PORT_MAIN}:81
      - ${PROXY_SSL_PORT}:443
    environment:
      - DB_MYSQL_HOST=mysql
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=root
      - DB_MYSQL_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - DB_MYSQL_NAME=npm
      - DB_MYSQL_SSL=false
      - DISABLE_IPV6=true
    depends_on:
      - mysql