version: '3.9'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - ${NPM_PORT}:80
      - ${NPM_PORT_ADMIN}:81
      - ${NPM_PORT_SSL}:443
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${NPM_DB_USER}
      DB_MYSQL_PASSWORD: ${NPM_DB_PASSWORD}
      DB_MYSQL_NAME: ${NPM_DB_NAME}
      # DISABLE_IPV6: 'true'
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./nginx-proxy-manager/data/log:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      phpmyadmin:
        condition: service_healthy
    networks:
      - env-server
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      FORCE_SSL: ${PMA_FORCE_SSL}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
      PMA_THEME: Bootstrap
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - env-server
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--log-error-verbosity", "--log-bin-index=/tmp/tmp.5FTdABPAKI"]
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NPM_DB_NAME}
      MYSQL_USER: ${NPM_DB_USER}
      MYSQL_PASSWORD: ${NPM_DB_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - env-server
networks:
  env-server:
    name: ${NETWORK_NAME}
    driver: bridge