version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NPM_DB_NAME}
      - MYSQL_USER=${NPM_DB_USER}
      - MYSQL_PASSWORD=${NPM_DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - env-server
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - FORCE_SSL=${PMA_FORCE_SSL}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
    depends_on:
      - db
    networks:
      - env-server
  nginx-proxy-manager:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - ${NPM_PORT}:80
      - ${NPM_PORT_ADMIN}:81
      - ${NPM_PORT_SSL}:443
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=${MYSQL_PORT}
      - DB_MYSQL_USER=${NPM_DB_USER}
      - DB_MYSQL_PASSWORD=${NPM_DB_PASSWORD}
      - DB_MYSQL_NAME=${NPM_DB_NAME}
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
      - phpmyadmin
    networks:
      - env-server
networks:
  env-server:
    name: ${NETWORK_NAME}
    driver: bridge
